# Etapa 1: Build
FROM node:18-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Etapa 2: Producción con Nginx
FROM nginx:stable-alpine

# Copia el build al directorio de Nginx
COPY --from=builder /app/dist /usr/share/nginx/html

# Copia archivo de configuración Nginx
COPY nginx.conf /etc/nginx/nginx.conf

# Expone el puerto por defecto de Nginx
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
