version: '3.8'

services:
  test-frontend:
    image: jonathanhuertascontreras/test-frontend
    container_name: container-test-frontend
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge 